version: '3'
services:
  db:
    image: postgres:12
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      -  POSTGRES_PASSWORD=password
  web:
    build: .
    env_file: .env
    image: mercali-clone:latest
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
      - node_modules:/myapp/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      WEBPACKER_DEV_SERVER_HOST: webpack-dev-server
  tailwindcss-watch:
    image: mercali-clone:latest
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
      - node_modules:/myapp/node_modules
    command: ["rails", "tailwindcss:watch"]
    tty: true
  webpack-dev-server:
    image: mercali-clone:latest
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
      - node_modules:/myapp/node_modules
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
      NODE_OPTIONS: --openssl-legacy-provider
    command: ./bin/webpack-dev-server
    ports:
      - "3035:3035"
    tty: true
volumes:
  bundle:
  node_modules: